apiVersion: v1beta1
id: haproxy1 
kind: Pod
namespace: default
desiredState:
  manifest:
    id: haproxy1
    version: v1beta1
    containers:
      - name: haproxy1
        image: localhost:5000/drupal
        ports:
          - Name: webport
            containerPort: 80
            hostPort: 80
